# the docker-compose.yml
version: "3"
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_HEAP_OPTS: "-Xmx12g -Xms12g"
      KAFKA_ADVERTISED_PROTOCOL_NAME: "INSIDE:PLAINTEXT"
      KAFKA_ADVERTISED_PORT: 9092
#      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: 192.168.8.103
#      KAFKA_ADVERTISED_NAME: 192.168.8.103
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "part1:1:1,part2:2:1,part4:4:1,part8:8:1,part16:16:1,pp:16:1,flink-classify-in:16:1,parteqin6:3:1,parteqout6:3:1,parteqfin6:3:1,parteqin12:6:1,parteqout12:6:1,parteqfin12:6:1,parteqin24:12:1,parteqout24:12:1,parteqfin24:12:1,parteqin48:24:1,parteqout48:24:1,parteqfin48:24:1,partbalin1:18:1,partbalout:30:1,partbalfin:30:1,partbalin2:12:1,partbalout2:36:1,partbalfin:36:1,partbalin3:6:1,partbalout3:42:1,partbalfin:42:1,partbalin4:47:1,partbalout4:47:1,partbalfin4:47:1"
